### ISSUE TITLE
(PROPOSAL) Can I redesign these websites?

### ISSUE THREAD

**Issue by ghost** [is-cool-me/is-epic.me#1]
ik its sounds weird, but its going to be like this

# Proposal
## One website repository for all domains
So, the repository is going to be on `website`. The source code is going to be https://github.com/vintheweirdass/is-cool.me (it uses [SvelteKit](https://svelte.dev) and a lighter Nodejs, [Deno](https://deno.com))

Why, may you ask?

Because im experimenting with my `ic_conf.json` file. Its already included with JSON Schema so your IDE can understand it (just watch the full video)

https://github.com/user-attachments/assets/1f2f25a5-b22c-4167-b1c5-40107738000d

Im going to do it like this

There would be an account for our 'bot' with the github PAT (or just use the ICME-BOT). The bot will be deployed when triggered with github actions (using manual `workflow_dispatch`). The github action will take out the domain that we passed it (eg, `is-app.tech`), and change the `selectedDomain` on `ic_conf.json` to that. After built using `deno task build`, the 'bot' takes the generated `.svelte-kit/generated/server` folder (its going to be static html with generated js files), and push it to their respective domains (like `is-not-cool/is-app.tech` and such)

Is this a good idea?

**Comment by ghost** [comment]
Btw you can programmatically add those 'not found' page, by adding the `+error.svelte` file inside `src/routes`. But that would be later

**Comment by LightHostingFree** [comment]
Bro I am already working on it see https://dash.is-cool.me

**Comment by LightHostingFree** [comment]
Just getting some errors if you can fix them I can make an maintainer of is-cool-me

**Comment by ghost** [comment]
> Bro I am already working on it see https://dash.is-cool.me

Oh shoot! I didnt know that

**Comment by ghost** [comment]
> Just getting some errors if you can fix them I can make an maintainer of is-cool-me

Hmm, ok i guess?

**Comment by ghost** [comment]
@LightHostingFree btw wheres the source code?

**Comment by ghost** [comment]
Closed. Im working with him to hunt the dashboard bug
